kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-volume
  labels:
    type: local
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pv-claim
  labels:
    app: minio
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
        tier: frontend
        track: stable
    spec:
      containers:
        - name: minio
          image: minio/minio
          args: ["server", "/data"]
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.store.minio.accessKey }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.store.minio.secretKey }}"
          ports:
            - containerPort: 9000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
    tier: frontend
  ports:
    - port: 9000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-port
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: {{ .Values.store.minio.nodePort }}
      protocol: TCP
