kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-volume
  labels:
    type: local
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pv-claim
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: minio
      tier: frontend
      track: stable
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: minio
        tier: frontend
        track: stable
    spec:
      containers:
        - name: minio
          image: localhost:32000/minio
          imagePullPolicy: {{ .Values.store.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.store.minio.accessKey }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.store.minio.secretKey }}"
            - name: CONSOLE_ADDRESS
              value: ":{{ .Values.store.minio.console.nodePort }}"
            - name: DATA_DIR
              value: "/data"
          ports:
            - containerPort: 9000
            - containerPort: {{ .Values.store.minio.console.nodePort }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
    tier: frontend
  ports:
    - name: api
      port: 9000
      protocol: TCP
    - name: console
      port: {{ .Values.store.minio.console.nodePort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-port
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: {{ .Values.store.minio.api.nodePort }}
      protocol: TCP
    - name: http2
      port: {{ .Values.store.minio.console.nodePort }}
      targetPort: {{ .Values.store.minio.console.nodePort }}
      nodePort: {{ .Values.store.minio.console.nodePort }}
      protocol: TCP
