apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: pgadmin
      tier: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: pgadmin
        tier: frontend
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "{{ .Values.pgadmin.password }}"
            - name: PGADMIN_DEFAULT_EMAIL
              value: "{{ .Values.pgadmin.email }}"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
    tier: frontend
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-port
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.pgadmin.nodePort }}
      protocol: TCP
