apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-store
  labels:
    app: postgres-store
data:
  POSTGRES_DB: {{ .Values.store.postgres.db }}
  POSTGRES_USER: {{ .Values.store.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.store.postgres.password }}
  DATASOURCE: "dbname={{ .Values.store.postgres.db }} host=postgres-store user={{ .Values.store.postgres.user }} password={{ .Values.store.postgres.password }} sslmode=disable"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-store
  labels:
    type: local
    app: postgres-store
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-store
  labels:
    app: postgres-store
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-store
spec:
  selector:
    matchLabels:
      app: postgres-store
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-store
    spec:
      containers:
        - name: postgres-store
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config-store
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim-store
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-store
  labels:
    app: postgres-store
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ .Values.store.postgres.nodePort }}
      protocol: TCP
  selector:
    app: postgres-store
