apiVersion: apps/v1
kind: Deployment
metadata:
  name: kebe-store
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: kebe-store
      tier: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: kebe-store
        tier: frontend
    spec:
      containers:
        - name: kebe-store
          image: "{{ .Values.store.image.registry }}/{{ .Values.store.image.repository }}:{{ .Values.store.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.store.image.pullPolicy }}
          command: ["/bin/kebe-store"]
          ports:
            - containerPort: 8080
          env:
            - name: KEBE_DATABASE_HOST
              value: {{ .Values.store.database.host }}
            - name: KEBE_MINIO_HOST
              value: {{ .Values.store.minio.host }}
---
apiVersion: v1
kind: Service
metadata:
  name: kebe-store
spec:
  selector:
    app: kebe-store
    tier: frontend
  ports:
    - port: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kebe-store-port
spec:
  selector:
    app: kebe-store
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.store.nodePort }}
      protocol: TCP
